### ISSUE TITLE
show 7 items instead of 8

### ISSUE THREAD

**Issue by Kadantte** [chirag-droid/animeflix#100]
As you can see in this picture the last anime shows just half

![image](https://user-images.githubusercontent.com/11579313/166504892-499e7c39-97a9-4d26-bcc8-817f76c58d43.png)

After using 7 it looks normal

![image](https://user-images.githubusercontent.com/11579313/166504957-ce3283f9-f1fd-4467-b929-afcbfa254b4d.png)

**Comment by chirag-droid** [comment]
Now they should be scrollable using arrow keys after hover. so it won't feel weird
