### ISSUE TITLE
500: Internal Server Error. Tried deploying on vercel.

### ISSUE THREAD

**Issue by animemandir** [chirag-droid/animeflix#105]
What I did :
- forked
- cloned
- minor ui changes
- deploy on vercel

![image](https://user-images.githubusercontent.com/78192713/167285614-841d992e-2d77-4d26-90d9-62223dd81535.png)
![image](https://user-images.githubusercontent.com/78192713/167285721-c40c956f-aa3c-4141-a5af-7bfff104866e.png)

I don't think the error is due to my mistake. Must be something about the code or vercel itself...

**Comment by chirag-droid** [comment]
No my deployment also showed this.

I think we would need to update the code for scraping gogoanime.

**Comment by chirag-droid** [comment]
Oh found the bug. This happened bcs of no testing. fixing

**Comment by chirag-droid** [comment]
fixed 🎉 .

Works on my machine.

**Comment by chirag-droid** [comment]
I am closing the issue, reopen if you face problem
