### ISSUE TITLE
New Feature: Countdown date/time when anime episode drops

### ISSUE THREAD

**Issue by adgsenpai** [chirag-droid/animeflix#112]
# New Feature: Countdown date/time when anime episode drops

Let's just say I am watching a new anime series that is airing.

I am currently watching example `episode 6 out of 12` whereas the other 6 never air yet. I would like a countdown timer suggesting when the next episode of the anime is coming out when viewing anime like that.

## For example 

![image](https://user-images.githubusercontent.com/45560312/167501220-d5e4dead-745d-46ea-91c3-e03f47c35c38.png)

When `episode 7` is coming out
![image](https://user-images.githubusercontent.com/45560312/167501291-ed53df8b-a59c-49c1-b283-246dfffc2888.png)

If you could add a grey block for `episodes 6-12` using my example above suggesting the date the episodes are coming out that would be cool.

All the best!
Hope you understand what I mean.

Keep up the good work guys!

**Comment by animemandir** [comment]
Yeah, hey Chirag, I made this code a while ago in simple js.
[https://jsfiddle.net/u3moa6y5/1/](https://jsfiddle.net/u3moa6y5/1/)

You can use it in nextjs right? would be easy.

**Comment by adgsenpai** [comment]
> Yeah, hey @chirag-droid , I made this code a while ago in simple js. It fetches the next episode air date exact to seconds just like in 9anime or animesuge.... https://jsfiddle.net/u3moa6y5/3/
> 
> You can use it in nextjs right? would be easy.

Beautiful, still busy with some industrial work if I got the opportunity I will contribute to the repo. If your guys contribute it before me that will work out better.

Beautiful Code seems simple to integrate. I will see what I can do if I got spare time.
Thanks a lot!

**Comment by chirag-droid** [comment]
> Yeah, hey @chirag-droid , I made this code a while ago in simple js. It fetches the next episode air date exact to seconds just like in 9anime or animesuge....
> [https://jsfiddle.net/u3moa6y5/3/](https://jsfiddle.net/u3moa6y5/3/)
> 
> You can use it in nextjs right? would be easy.

Yeah. Also I am currently reworking on some part of the code relating to graphql. after that I will implement this

**Comment by animemandir** [comment]
btw, check the ui and functions of this one - [https://weebflix.netlify.app/](https://weebflix.netlify.app/)
Can add tv, movies, ova section like this?
source code - [https://github.com/animemandir/nuxt-weebflix-animelist](https://github.com/animemandir/nuxt-weebflix-animelist)

**Comment by riimuru** [comment]
#125
