### ISSUE TITLE
Unusable jsdelivr CDN in China

### ISSUE THREAD

**Issue by lwd-temp** [chirag-droid/animeflix#151]
**Describe the bug**
Some of the player resource loaded is from `cdn.jsdelivr.net`, which is blocked in China. I find it difficult to switch it to `unpkg.com`.

**To Reproduce**
1. Go to any anime
2. Click on 'Play'
3. Player won't load because `https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js` etc. is blocked.

**Expected behavior**
Change the CDN through source code.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge
 - Version [8346dd9](https://github.com/chirag-droid/animeflix/commit/8346dd978b0d164fc84ffbe31fa8a027b7bda74a)

**Comment by lwd-temp** [comment]
This is almost impossible because the actual CDN used is defined by `@vime/react` and may not be modified through build settings etc.

**Comment by riimuru** [comment]
@lwd-temp unfortunately, the only way to get passed this is to use a VPN.

**Comment by chirag-droid** [comment]
Or to open an issue on @vime/react or make a fork of @vime/react and modify it.

**Comment by chirag-droid** [comment]
The only thing that could possibly work is by using a service worker, but the app already uses a service worker

**Comment by lwd-temp** [comment]
> Or to open an issue on @vime/react or make a fork of @vime/react and modify it.

That's right. This should be reported to `@vime/react`.

**Comment by chirag-droid** [comment]
I opened a pull request there - vime-js/vime/#313

**Comment by chirag-droid** [comment]
@lwd-temp can you verify if fastly.jsdelivr.com works?
