### ISSUE TITLE
Client Side Error

### ISSUE THREAD

**Issue by casualGamer-dev** [chirag-droid/animeflix#158]
**Describe the bug**
Client Side error on 

**To Reproduce**
1. Go to 'Jujustu kaisen 0
2. Click on 'click on watch now

**Comment by chirag-droid** [comment]
Oh that movie isn't listed on gogoanime too

**Comment by chirag-droid** [comment]
I have fixed so it won't show client side error. but you still can't play as its not listed on gogoanime

**Comment by chirag-droid** [comment]
You can watch Jujutsu Kaisen tho, which is a tv series
