### ISSUE TITLE
Visual bug on `Recommended animes` + Use of other databases

### ISSUE THREAD

**Issue by NWJ9PB** [chirag-droid/animeflix#16]
I know this is already obvious, as it is seen on almost every page, Please address this issue

And on the `other databases`, Can you utilize the use of MAL, or other databases, as it is the cause of some anime to be returning `404` on some anime with multiple title variations,

**Comment by NWJ9PB** [comment]
What if use the AniList just for the synopsis of the content, and use another for the title lookup, So that the failure of the lookup is low

**Comment by NWJ9PB** [comment]
On the AniList issue, try [Jinkan.moe](https://jikan.moe/), As it uses MAL for lookup, But It doesnt have any banner for the title image preview

**Comment by chirag-droid** [comment]
Now the visual bug should hopefully be gone. and here the implementation for getting video links #74
