### ISSUE TITLE
Is vercel is free?

### ISSUE THREAD

**Issue by sunilroyy007** [chirag-droid/animeflix#17]
Is vercel is free to deploy?  Also can you give support to deploy on heroku.com

**Comment by chirag-droid** [comment]
Vercel is free.

**Comment by sunilroyy007** [comment]
> Vercel is free.

Its asking for phone number to use. Can you provide support for other sites? Can i also use this to gather movies? Can you guide me how to do that if possible

**Comment by NWJ9PB** [comment]
@sunilroyy007 Just use github as a sign-in/sign-up method, and It will not probably ask for phone numbers

**Comment by sunilroyy007** [comment]
> @sunilroyy007 Just use github as a sign-in/sign-up method, and It will not probably ask for phone numbers

I did used GitHub but it still asked for phone number

**Comment by NWJ9PB** [comment]
@sunilroyy007 Probably you didn't use a phone number for 2FA method, On that case, phone number is a must

**Comment by sunilroyy007** [comment]
> @sunilroyy007 Probably you didn't use a phone number for 2FA method, On that case, phone number is a must

We will be safe for hosting this right? No weird shit or any legal shit for us

**Comment by NWJ9PB** [comment]
@sunilroyy007 I believe hosting this repo on their services are in a gray area, It is not *Illegal* as the repo doesn't actually host the materials, just like nyaa.si or TPB,

**Comment by sunilroyy007** [comment]
> @sunilroyy007 I believe hosting this repo on their services are in a gray area, It is not _Illegal_ as the repo doesn't actually host the materials, just like nyaa.si or TPB,

Can we also use this for movies?

**Comment by NWJ9PB** [comment]
It might be possible, but that requires recode of the referrence database *(Current is AniList)* and the Source *(Current is gogoanime)*

**Comment by sunilroyy007** [comment]
> It might be possible, but that requires recode of the referrence database _(Current is AniList)_ and the Source _(Current is gogoanime)_

Thank you
