### ISSUE TITLE
How to start this application with PM2?

### ISSUE THREAD

**Issue by flaxplax** [chirag-droid/animeflix#18]
Im not a developer. I was looking for something like index, app, server and cannot seem to find it.
how would i start this application in a process manager? either with PM2 or systemd?

**Comment by NWJ9PB** [comment]
@flaxplax Based on PM2 docs (https://pm2.keymetrics.io/docs/usage/quick-start/)
Just do `pm2 start <FILENAME>`

**Comment by imlarx** [comment]
@flaxplax Looks like you can not run next.js apps using pm2. Since next.js builds the source on the fly and deploys it.

**Comment by flaxplax** [comment]
I ended up creating a simple systemd service that runs a bash script.
script
```
#! /bin/bash
npm run start
```
service
```
[Unit]
Description=AnimeFlix

[Service]
User=root
WorkingDirectory=/root/animeflix
ExecStart=/root/animeflix/run.sh
Restart=always

[Install]
WantedBy=multi-user.target
```
works great btw ^^
