### ISSUE TITLE
GogoAnime now added AWS Cloudfront MP4 urls.

### ISSUE THREAD

**Issue by 0zul** [chirag-droid/animeflix#20]
Gogoanime recently added AWS Cloudfront mp4 URL. It should be accessible in the same way how it's being proxied just like m3u8 stream links.

**Comment by chirag-droid** [comment]
ok, will try that. I will see if it will need a proxy or not

**Comment by imlarx** [comment]
Are you on Discord? Cuz I'd like to talk to you more and get to know you. As for whether it needs a proxy or not...well I think it does because those are encrypted ig.
