### ISSUE TITLE
Error on deploying to Vercel

### ISSUE THREAD

**Issue by dakshy** [chirag-droid/animeflix#221]
**Describe the bug**
`Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory`

**To Reproduce**
1. Deploy the repo using the vercel deploy button given in Readme.md
2. See error

**Expected behavior**
Of course, I wish to deploy the site.

**Screenshots**
![image](https://user-images.githubusercontent.com/67213740/181042680-4396fbe2-05fc-46b9-aea0-e8be8764c04f.png)

**Desktop:**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
Currently, not able to deploy it on Vercel.

**Comment by chirag-droid** [comment]
I am currently using a monorepo structure. Set your output directory to frontend and see if that works

**Comment by dakshy** [comment]
> 

After changing Output Directory to `frontend`.
![image](https://user-images.githubusercontent.com/67213740/181044907-69823c1d-9591-4366-9616-14b266504f2a.png)

**Comment by Najidnadri** [comment]
Not sure why this is closed without any solution.

However, I solved this problem by just changing the `framework preset` of the project in the project's settings to `next js`. After that, just redeploy the project.

You setting should looks like this:
--Build & dev settings--
Framework Preset: Next.js
Build Command(override): cd ../ && yarn build

--Root Directory--
frontend

--Node.js Version--
18.x
