### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by gnrlk3nobi** [chirag-droid/animeflix#24]
Hiya, is it possible for simple keyboard shortcuts for video playback to be added? Such as spacebar to pause/play, right/left arrow to skip forward/backward, up/down arrow for volume and so on. 

It would also be nice if we can choose how many seconds it skips forward/backward to, like between 5 seconds to 15 seconds.

Thanks!

**Comment by animemandir** [comment]
Oh that's nice suggestion. I'll try to do that within 2 days. I'm trying to improve this project a bit - https://ani-toons.vercel.app/
there are many bugs and ui glitches which I'll fix in a week or so.

**Comment by chirag-droid** [comment]
This issue is now fixed in #101
