### ISSUE TITLE
Videos won't play in some regions without proxy.

### ISSUE THREAD

**Issue by chirag-droid** [chirag-droid/animeflix#87]
The videos sometimes fail to work without proxying requests. The issue however doesn't occur when hosted on Vercel tho.

**Comment by TomRomeo** [comment]
Many videos didn't work without the proxy for me either. That's why I decided to route them through it in my pr.
I think if I remember correctly, the issue primarily came from mp4 files, not hsl files.
Is there any major drawback from just proxying all video urls?

**Comment by chirag-droid** [comment]
Well for example if I try to play Stein's gate, it will fail. I am getting this [url](https://www08.gogocdn.stream/videos/hls/tj2jLr4O5Cij1LigfwmoIg/1651442625/38317/c835f014b066080a586404230052d405/ep.1.1645521584.m3u8). If this request is proxied it becomes

api/video/?src={link}&referer={referer}

Now the hls file specifies video link relative to the original link. So if it points to ./video-file

the request is sent to api/video/video-file instead or api/video?src{link/video-file}&referer={referer}

Thus it fails.

**Comment by chirag-droid** [comment]
I think I found a temporary fix. I am assuming gogocdn links work without proxy

**Comment by riimuru** [comment]
> Well for example if I try to play Stein's gate, it will fail. I am getting this [url](https://www08.gogocdn.stream/videos/hls/tj2jLr4O5Cij1LigfwmoIg/1651442625/38317/c835f014b066080a586404230052d405/ep.1.1645521584.m3u8). If this request is proxied it becomes
> 
> api/video/?src={link}&referer={referer}
> 
> Now the hls file specifies video link relative to the original link. So if it points to ./video-file
> 
> the request is sent to api/video/video-file instead or api/video?src{link/video-file}&referer={referer}
> 
> Thus it fails.

why not just make people be able to choose different server, we have hls and mp4.

**Comment by chirag-droid** [comment]
Yeah this is better. thnx

**Comment by chirag-droid** [comment]
> @chirag-droid Let's give people the option of using a separate server gogocdn/vidstreamcdn, as we have hls and mp4 formats. Let's also give the user the option to add/remove proxy to the video if it doesn't work.

@riimuru I implemented the ability to choose if they want to proxy the video or not in #92.
