### ISSUE TITLE
Logo / Favicon

### ISSUE THREAD

**Issue by TomRomeo** [chirag-droid/animeflix#88]
### It would be nice to add a Logo / Favicon to this project.

I came up with some Logos that are _heavily_ inspired by the Netflix logo.

I am not exactly satisfied with them and it might be problematic to use the Netflix color palette. Maybe you guys have a completely different idea for a Logo aswell. I just wanted to start a discussion :smile:

---

| Thin | Bold |
|-|-|
| <img width=200px src="https://user-images.githubusercontent.com/60541979/166146467-4ddebde9-b81b-42eb-bdd7-a7145268fa0e.png" /> | <img width=200px src="https://user-images.githubusercontent.com/60541979/166146507-97878399-b460-43ea-847b-a1ae4405527c.png" /> |

---

**PS: The inkscape .svg files are attached below**
They might seem buggy in the preview but work fine when imported into inkscape.
[animeflix_fat](https://user-images.githubusercontent.com/60541979/166146922-7aed7d5f-0c92-4a3c-9db9-895c6a781970.svg)
[animeflix](https://user-images.githubusercontent.com/60541979/166146923-5924bcc9-204c-45fc-8dbf-04a34af46794.svg)

**Comment by chirag-droid** [comment]
I added these icons #91. 

Also I opened it using figma and exported, now it works when opening in browser too. It also compressed the svg. [icon](https://user-images.githubusercontent.com/81347541/166202962-e4da96ec-cbf7-4745-adbf-8bde2acc490e.svg)

**Comment by TomRomeo** [comment]
Nice, then I'll close the issue :)
