### ISSUE TITLE
Feature: Show a list of episodes and seasons for anime

### ISSUE THREAD

**Issue by adgsenpai** [chirag-droid/animeflix#95]
There is no option for showing list of episodes for anime. Please add that feature. 

Thanks

**Comment by riimuru** [comment]
Yes, we're working on it. check the [discussion](https://github.com/chirag-droid/animeflix/discussions/84).

**Comment by chirag-droid** [comment]
I reopened it, its kinda useful for me to see what I need to work on by looking at features. Will close after its finally implemented.

**Comment by TomRomeo** [comment]
Where do you plan to get the episode information from?
As far as I can see there is a `streamingEpisodes` entry in anilist but I am not sure if it is [reliable enough](https://anilist.co/forum/thread/23973)

Also, what do you think about including character information on the anime site aswell (such as character names and voice actors)?

**Comment by chirag-droid** [comment]
there is an `episodes` entry too which just returns the number of episodes, although it may return null for currently running shows

**Comment by riimuru** [comment]
@TomRomeo kitsu is reliable enough

**Comment by riimuru** [comment]
@chirag-droid I will write the function that returns the episodes accurately, so can you build the ui and the card component for the episode?

**Comment by chirag-droid** [comment]
Can you tell me what api you are going to use?

If you are going to use kiitsu, then verify if it can return episodes number for currently running animes too.

**Comment by riimuru** [comment]
I will be using kitsu. 

Yes, i will verify if it returns the right number of episodes correctly, if its not accurate then i will use my api to get the number of episodes needed.

**Comment by chirag-droid** [comment]
@riimuru wait let me make a discord server. so we all can work together

**Comment by chirag-droid** [comment]
@riimuru Join this server https://discord.gg/4UPU8etvae

**Comment by chirag-droid** [comment]
I have implemented the episodes list thing now

**Comment by riimuru** [comment]
@chirag-droid i just opened a pull request which should fix episode list being null on active anime.

**Comment by TomRomeo** [comment]
This feature was implemented by 5921e252ff6031597ee7490e4a188c26212f1bed and #108 
so I think we can close this issue now @chirag-droid :)
